### ISSUE TITLE
express 的一个小疑问

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#10]
我刚仔细看了一下 express 觉得我们可以这样搞嘛：

express handle 两个系列的路由，

一个是 `/` 
一个是 `/api/:apiParams` 

然后我从 `/api/:apiParams` 这里拿数据，写数据。。

这样一来，就也不用考虑跨域，没状态这种事情了 right ？

然后我的页面无非也就是全写到 `/` 对应的页面里就好了嘛

我这么理解没错吧？

**Comment by zhuangya** [comment]
而且如果是这样搞的话我也就不需要再开 Ophiuchi 这个名字我自己都记不住的 repo 了。。。囧rz

**Comment by bearice** [comment]
是的，即使不用express 用nginx rewiite一下也就可以了
