### ISSUE TITLE
网站设计图

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#11]
@zhuangya @bearice 网站设计图出来啦 甲方已通过 大家请过目 不断完善中。。。

benzex-homepage
![benzex-homepage](https://f.cloud.github.com/assets/4066386/1665476/bafe07bc-5c37-11e3-8a04-822a74ca125b.jpg)

---

benzex- 新品&网上商店
![benzex-](https://f.cloud.github.com/assets/4066386/1665481/cd034238-5c37-11e3-9401-9a11bd3e495d.jpg)

---

benzex- lookbook
![benzex- lookbook](https://f.cloud.github.com/assets/4066386/1665483/d300739a-5c37-11e3-9699-285ace98c787.jpg)

---

benzex-我的订单
![benzex-](https://f.cloud.github.com/assets/4066386/1665487/db04ac1e-5c37-11e3-960a-b4a77fcf52a3.jpg)

---

benzex-精选视频
![benzex-](https://f.cloud.github.com/assets/4066386/1665488/db32a312-5c37-11e3-9491-56867fa3e8c5.jpg)

---

benzex-联系我们
![benzex-](https://f.cloud.github.com/assets/4066386/1665489/db5ff70e-5c37-11e3-9812-670d43fc1ef4.jpg)

---

benzex-个人中心
![benzex-](https://f.cloud.github.com/assets/4066386/1665490/db7b8820-5c37-11e3-86c0-e74d1052c427.jpg)

**Comment by wan9** [comment]
请按照设计认真修改 明确指出如下-

## 所有页面：
- [x] 左侧导航栏字体请修改为14px，右侧导航两个请修改为16px。
- [x] 请在除了新品页面的其他所有页面的右侧导航旁添加benzex logo，可点击返回首页。

## 新品页面：
- [ ] 新品页面中间衣服栏，请添加剩余衣服，按照设计修改。在鼠标放上去显示衣服的名称，价格，与加入购物车。
- [ ] 请按照设计把新品页面中间衣服栏上黑色框部分加宽，点击benzex logo能够返回到首页。benzex下加横线，加join a weird trip.图我稍后马上给出。
- [x] 请按照设计在新品页面中间衣服栏上黑宽部分加上头像，名字修改为白色，在我的订单和个人中心下加上注销按钮。在点击后弹窗询问是否确定注销此帐号。
- [x] 在新品中间栏最下加上三点按钮表示下拉刷新更多。

## 单品页面：
- [x] 单品页面选择加入购物车后无反映。加入购物车改黑色，不需做按键 ，依旧请根据设计修改，并在后面添加下一件。进入购物车可通过点击我的订单页面查看。在页面底部添加头像，我的订单，个人中心与注销键。
- [x] 单品页面的名称和价格尺码等的样式请按照设计来写。衣服名称的字体请加大到18px。无需显示类别。

## 精选视频：
- [ ] 请先添加一个视频作为测试，例如 http://v.youku.com/v_show/id_XNjY4MjExMjM2.html  名字可先写random video，并在下添加灰色other键可点击至下一个推荐视频（可任选）。
- [x] 请按照设计在下左下角添加头像组合（头像，名字，我的订单，个人中心，注销）。

## 联系我们：
- [x] 请把中间的黑框加宽至等同新品页面中栏同等宽度。
- [x] 同在页面左下角添加头像组合。

## 个人中心：
- [x] 请在页面中间添加适当黑框，即使没有选择任何衣服也请在左侧显示：您还未挑选任何衣服，随便看看。可点击跳至新品页面。同样不要做成按键。文字显示即可。
- [x] 按照设计图用白线划分出侧栏，上方有头像组合下方有total与其他具体请严格参照设计。

## 我的订单：
- [x] 同样要求不用各种框 在点击后面编辑时候才显示可以输入的框。
- [x] 同样要求按照设计图添加其他。

请严格按照设计修改，无需自创样式。有任何问题任何要求请提出，不要再拖拉。

**Comment by wan9** [comment]
@zhuangya @bearice 
请二位最近辛苦下，把这回10号的deadline当回事，毕竟拖了一个多月了，按照这样以后肯定也不会合作了。就当最后一次为了我们合作一起努力下。别让甲方天天把我说哭行么，我求求你俩了这回。

**Comment by zhuangya** [comment]
> 在新品中间栏最下加上三点按钮表示下拉刷新更多。

下拉刷新？

**Comment by zhuangya** [comment]
> 新品页面中间衣服栏，请添加剩余衣服，按照设计修改。在鼠标放上去显示衣服的名称，价格，与加入购物车。

鼠标 hover 的部分，界面已经好了。
但是从这里加入购物车，目前的结构来看，有点困难，难道不选尺寸和规格了嘛？

**Comment by zhuangya** [comment]
> 单品页面选择加入购物车后无反映。加入购物车改黑色，不需做按键 ，依旧请根据设计修改，并在后面添加下一件。进入购物车可通过点击我的订单页面查看。在页面底部添加头像，我的订单，个人中心与注销键。

下一件需要 api 支持一下 cc @bearice

**Comment by zhuangya** [comment]
> 单品页面的名称和价格尺码等的样式请按照设计来写。衣服名称的字体请加大到18px。无需显示类别。

**无需类别显示** 的意思是说，所有的衣服就只有号码的区分，而没有颜色/规格的区分？

**Comment by zhuangya** [comment]
> 联系我们：
> 
> 同在页面左下角添加头像组合。

什么意思？
