### ISSUE TITLE
域名就绑定上好了我觉得。

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#13]
直接扔到 benzex.com 那个域名上测试吧。

也好让爬虫刷一刷。（当然，根本是，这种网站反正也无所谓的。。

**Comment by bearice** [comment]
域名和自动部署已经就绪

`git remote add production git@icybear.net:/data/git/nova.git` (你的Key应该已经添加了)

使用 `git push production master` 部署到线上

另外frontend的生成目录改到了 `../webroot` 里

**Comment by zhuangya** [comment]
好的 收到
