### ISSUE TITLE
首页和各个子页面的地址。

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#14]
@wan9 图贴这里。

**Comment by wan9** [comment]
![shutterstock_108809924](https://f.cloud.github.com/assets/4066386/1703798/4fe98b20-60bc-11e3-9ed3-ba54b9a51831.jpg)
首页图

**Comment by wan9** [comment]
![benzex-tm-](https://f.cloud.github.com/assets/4066386/1724949/9faec626-6278-11e3-964e-87b28dfd9cdb.png)
LOGO
