### ISSUE TITLE
weibo auth 之后 mongo 报了个错

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#23]
<pre><code>
MongoError: E11000 duplicate key error index: 
nova.users.$email_1 dup key: { : null } at 
Object.Future.wait 
(/data/nova/node_modules/fibrous/node_modules/fibers/future.
js:326:15) at model.synchronize 
(/data/nova/node_modules/fibrous/lib/fibrous.js:63:47) at 
Object.proxyBuilder [as save] 
(/data/nova/node_modules/fibrous/lib/fibrous.js:98:47) at 
app.post.passport.authenticate.req.account 
(/data/nova/src/auth.coffee:208:6) at callbacks 
(/data/nova/node_modules/express/lib/router/index.js:164:37)
 at fibrous.middleware 
(/data/nova/node_modules/fibrous/lib/fibrous.js:167:18) - - 
- - - at Object.toError 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/utils.js:110:11) at 
/data/nova/node_modules/mongoose/node_modules/mongodb/lib/mo
ngodb/collection.js:345:24 at Server.Base._callHandler 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/connection/base.js:382:41) at 
Server.connect.connectionPool.on.server._serverState 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/connection/server.js:472:18) at MongoReply.parseBody 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/responses/mongo_reply.js:68:5) at 
Server.connect.connectionPool.on.server._serverState 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/connection/server.js:430:20) at EventEmitter.emit 
(events.js:96:17) at _connect 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/connection/connection_pool.js:191:13) at 
EventEmitter.emit (events.js:99:17) at 
Socket.exports.Connection.createDataHandler 
(/data/nova/node_modules/mongoose/node_modules/mongodb/lib/m
ongodb/connection/connection.js:384:22)
</code></pre>

**Comment by zhuangya** [comment]
#22

**Comment by bearice** [comment]
这是线上报错还是你本机的报错？

**Comment by zhuangya** [comment]
线上
