### ISSUE TITLE
video api interface format.

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#24]
熊叔，我期望 video 的 api 返回的结果是这样：

``` json
[{ "name": "mac pro 开箱",
   "url": "http://v.youku.com/v_show/id_XNjUwNjIxNDA0.html"
}, { ... }]
```

其中  `name` 是我这边提交给你的 :)

**Comment by bearice** [comment]
没搞懂
不过我觉得这个其实弄一个json文件就好了啊，又不会同时有几K个视频。

**Comment by zhuangya** [comment]
我的意思就是，这是一个 json ，然后最外层，是一个 array `[]`

然后 array 中的每一个项目是包含两个key
- `name`
- `url` 

的一个 `hash`

我在存 video 的时候，存的就是 

``` json

{ "name" : "name of the video",
  "url": "video's youku url"
}

```

这样给你的啦 :)

**Comment by bearice** [comment]
了解了，待会儿我弄下，

2013/12/24 Ya Zhuang notifications@github.com

**Comment by bearice** [comment]
closed in 9d3c47e
