### ISSUE TITLE
the api for testing.

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#3]
少年，来搞一个资源的接口，比如就叫 `/testing` 目前要求就俩：
- 跨域支持 （虽然这货可以在 nginx 里做，但是反正也不复杂，就先扔 node 里吧，毕竟想换也好换）
- 返回我请求的方法，比如： `get testing` `post testing` etc..

**Comment by bearice** [comment]
see http://nova.icybear.net/api/test
