### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#34]
最近忙成屎了。。。延期了这么久感觉超级不好的。。= =
不过还是让我先整理一下现在还需要搞的事情吧
- [x] admin 增加衣服的流程我这里还有点小问题，@bearice 我把我这里梳理一下之后再问问你好了> < ...
- [x] weibo 认证的前端信息的显示 这里因为 weibo callback 的缘故我这里不是很好测试， @bearice 你先改成 lo.benzex.com 这个域名上的 callback 如何？所以我就可以加个 nginx 和 host 了。。
- [x] 购物车的部分的界面

还有什么要做的  @bearice @wan9 就加在这里吧先。

**Comment by bearice** [comment]
关于第二点，你在本地起一个服务 然后在host里添加 127.0.0.1 test.benzex.com 就好了，callback会自动适配的。
