### ISSUE TITLE
线上又冲突了？

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#39]
好像我这里 push production master 又失败了。。

**Comment by bearice** [comment]
没发现啊，什么现象？

**Comment by zhuangya** [comment]
代码更新不上去，不然你试试？？

**Comment by bearice** [comment]
很顺利的push上去了口牙，一定是你打开的姿势不对

**Comment by zhuangya** [comment]
yeoman/generator-angular#558

唉。。
