### ISSUE TITLE
申请支付宝API

### ISSUE THREAD

**Issue by bearice** [zhuangya/nova#4]
我的账户根本打不开它的测试网站 (http://sandbox.alipaydev.com/index.htm )，需要对方提供一个认证账号。

http://club.alipay.com/simple/?t10756607.html

问：入驻支付宝开放平台需要符合哪些资质？ 
答： 
1） 开发者需为具有法人资格的企事业单位，且必须通过完整的支付宝实名认证（身份认证+银行卡认证）。 
2） 开发者注册资金10万元及以上且公司已正常经营一年以上； 
3） 开发者需有固定办公场所。 
4） 如果是淘宝开放平台应用，则需要部署在聚石塔。 
有下列任一情况的用户不允许入驻： 
1）注册与实际经营不符的商户； 
2）实际存在或涉嫌非法经营、违规经营的开发者； 
3）开发者法定代表人具有严重违法或不良信用记录的开发者（例如：网络上存在负面新闻报道） ； 
4）经过风险管理部认定的高风险类型商户。

**Comment by zhuangya** [comment]
@wan9 你明天联系一下，看看这个事情，让他们那边处理一下。

**Comment by zhuangya** [comment]
@bearice 来贴一下 支付宝 那边的需求
@wan9 来跟一下这个事情 push zhangchi 那边

**Comment by bearice** [comment]
支付宝签约步骤 http://act.life.alipay.com/shopping/before/help/index.html

**Comment by zhuangya** [comment]
@wan9 https://b.alipay.com/order/productDetail.htm?productId=2012111200373121&tabId=1#ps-tabinfo-hash 给zhangchi 直接看这个吧。

**Comment by zhuangya** [comment]
Zhang Chi 那边申请了 http://fun.alipay.com/zfbxt/qianyueditu.htm?src=nsf04 这个服务，但是没成功。
支付宝那边要求网站有登录功能，以及到 taobao 的 link 。

先不说上面那些，但是总感觉这个事情，如果是我们要自己做购物车的话，那就一定要申请 api 对吧？ @bearice 
然后 api 又一定要公司认证的帐号才可以申请。

所以，即使上面那个申请成功了，感觉也是一个 link 到淘宝的感觉。。。
sigh

我先赶紧把界面搭一搭再来搞这个事情好了。。 shrug

**Comment by zhuangya** [comment]
熊叔，辛苦一下，现在看看这个事情能不能跟进吧　:)

@bearice

**Comment by wan9** [comment]
zhangchi那边已经在申请支付宝api
这里是担保交易的一些要求 我们都符合 辛苦啦
![f9 m20_1 sdu7 oqhj9fx2](https://f.cloud.github.com/assets/4066386/2157083/a6a91faa-9471-11e3-9514-8567a343fa31.jpg)
