### ISSUE TITLE
微博接口信息

### ISSUE THREAD

**Issue by bearice** [zhuangya/nova#42]
需要以下信息：

![screen shot 2014-02-01 at 0 43 43](https://f.cloud.github.com/assets/270121/2052449/2771d04e-8a97-11e3-9316-a41713ae2378.png)

（其中简介图片需要三张）

**Comment by wan9** [comment]
![16 benzex](https://f.cloud.github.com/assets/4066386/2057902/9492628e-8b54-11e3-979e-2d0f21f867c4.jpg)
![80 benzex](https://f.cloud.github.com/assets/4066386/2057903/94ca537e-8b54-11e3-96dd-cd7e7f33c6fe.jpg)
![120 benzex](https://f.cloud.github.com/assets/4066386/2057904/94d13d9c-8b54-11e3-9e0a-12df940bb0fd.jpg)
![1](https://f.cloud.github.com/assets/4066386/2057907/ad29b644-8b54-11e3-9620-f19f006b13fc.png)
![benzex-8](https://f.cloud.github.com/assets/4066386/2057908/ad9db2f6-8b54-11e3-8c61-be6dc3e92267.jpg)
![item](https://f.cloud.github.com/assets/4066386/2057909/adcbc1e6-8b54-11e3-9e94-3ce280fc38fa.jpg)

**Comment by zhuangya** [comment]
@bearice 熊叔你来看看，另外 @wan9 标签的事情呢？

**Comment by bearice** [comment]
> 你的应用“BENZEX”来源审核中
> 审核结果将在一个工作日内反馈（如遇特殊情况，审核周期将会相应延长），您可以联系@微博开放平台 咨询审核进度

**Comment by zhuangya** [comment]
赞

**Comment by bearice** [comment]
> 尊敬的开发者您好：
> 　　您的应用“BENZEX”未能通过我方的来源文案审核，其原因是：“应用类型选择不正确，请创建网站接入重新提交”。请您依据我们的建议和《微博开放平台审核指南》，再次修改后重新提交审核申请。查看常见驳回理由说明及解决方案 http://t.cn/zluaxfa。感谢您对新浪微博开放平台的支持！

will retry later

**Comment by bearice** [comment]
> 2、ICP备案号
> A、如果您是境内网站，请选择“境内网站”，并提供ICP备案号，且该ICP备案号需与申请网站页面显示的一致，不提供ICP
> 的境内网站将不会通过审核；
> B、如果您是境外网站，选择“境外网站”即可，不需要填写ICP备案号。但是需要上传境外网站证明扫描件。

**Comment by bearice** [comment]
> 我们正在审核您的网站，审核时间通常为一个工作日（如遇特殊情况，审核周期将会相应延长），您可以联系@微博开放平台 咨询审核进度。

**Comment by wan9** [comment]
点赞

**Comment by bearice** [comment]
> 尊敬的开发者您好：
> 　　您的应用“benzex”已经通过我方的来源文案审核，经由您的应用所发出的微博信息将会显示相应的来源文案，同时，您可以查看《微博开放平台审核指南》，对您的应用进行优化。感谢您对新浪微博开放平台的支持！
