### ISSUE TITLE
admin api 删除衣服的时候， memcached 没更新？

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#43]

**Comment by zhuangya** [comment]
`POST http://test.benzex.com/api/admin/data/animal/cat/delete`

到这里的时候，返回了这个被删除的衣服的信息，然后重新获取衣服的列表的时候，这个还在

但是再次删除的时候，就500了。

**Comment by bearice** [comment]
删除了以后你reload cache了么？

2014-02-05 Ya Zhuang notifications@github.com:

**Comment by zhuangya** [comment]
> 删除了以后你reload cache了么？

how to ？
