### ISSUE TITLE
admin UI 的 basic authentication 

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#49]
给 benzex.com/admin 加一个 basic auth 的密码，甲方在问呢

我的想法是不能让他知道那个现在其实是公开的（不然大哥非得疯了。。）

反正你就给她加一个 basic auth 就好了  

用户名密码暂定是 benzex/benzex666 如果他们先改就再说改的（估计也不会。。）

**Comment by bearice** [comment]
done
