### ISSUE TITLE
网站备案到北京来

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#56]
张驰那边要求网站备案到北京来 方便享受一些政策这样 不是之前我们准备在美团云搞么？
看看还有什么需要的

**Comment by zhuangya** [comment]
@bearice 部署在 美团云上？现在你还有那个主机没？

**Comment by bearice** [comment]
美团云的主机还在，但是不知道能用多久。

**Comment by zhuangya** [comment]
没事，过期了我来续费便是了。

**Comment by bearice** [comment]
我先改解析然后nginx反代过去吧，等最后弄好了再把代码部署过去？

**Comment by zhuangya** [comment]
ok, np
close it for now.

**Comment by wan9** [comment]
@bearice 熊叔 网站备案的事情怎么样了~？甲方那边在催了

**Comment by wan9** [comment]
@bearice 
![2014-02-22 4 46 23](https://f.cloud.github.com/assets/4066386/2237294/dfa61244-9b9d-11e3-97c9-f2ef84215ccb.png)
![2014-02-22 4 47 28](https://f.cloud.github.com/assets/4066386/2237301/26c75304-9b9e-11e3-8854-058b73bff845.png)

这里是我们申请官方认证需要的东西

**Comment by zhuangya** [comment]
@wan9 https://mos.meituan.com/docs/beian.html 参考这里联系张驰准备材料

**Comment by wan9** [comment]
@zhuangya @bearice 
跟甲方那边谈过 基本崩 由我们来买美团云主机 
美团云的帐号我们选择最低的费用应该是1060

**Comment by zhuangya** [comment]
删了一些敏感信息（因为现在这个 repo是公开的。。）
另外，备案的这个事情就走到美团或者其他 agent 的流程吧。 closing this
