### ISSUE TITLE
支付宝已申请成功 请完成接口集成

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#58]
@zhuangya 
![b1a0f8cd-5359-4100-8f7a-f26d4eec8115](https://f.cloud.github.com/assets/4066386/2168454/498940ec-953f-11e3-83a2-fe35090f96fe.jpg)

**Comment by bearice** [comment]
需要提供PID和KEY

**Comment by wan9** [comment]
@bearice 
是不是我们走第二个那个自助集成 然后让zhangchi那边下载集成文档传给我们 
然后再给我们提供PID和KEY

**Comment by bearice** [comment]
需要提供

```
partner:'' //合作身份者id，以2088开头的16位纯数字
,key:''//安全检验码，以数字和字母组成的32位字符
,seller_email:'' //卖家支付宝帐户 必填

```

**Comment by wan9** [comment]
集成文档：http://club.alipay.com/read-htm-tid-9976972.html

![dp_3o b t zax d8ya_4_ 4](https://f.cloud.github.com/assets/4066386/2168606/d972c7b4-9544-11e3-9472-e8aca4867685.jpg)

zhangchi的支付宝帐号为： 1147880393@qq.com

**Comment by bearice** [comment]
能不能吧文本发来我直接copy....

**Comment by wan9** [comment]
2088112013489272

6s8icmlbltaqrpowwuarthqojud5lo01

**Comment by zhuangya** [comment]
alipay api kick off :)
