### ISSUE TITLE
提交购物车到支付宝

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#59]
熊叔，我发给你什么格式的数据？

我刚大概想了一下，需要的数据有
- 收货地址
- 钱
- 手机号码
- 买了什么衣服 [ ] 

还有其他的没？

**Comment by bearice** [comment]
你只需要提交地址（包括电话），其他根据购物车生成。

2014-02-14 15:43 GMT+08:00 Ya Zhuang notifications@github.com:

**Comment by zhuangya** [comment]
这个好了没？甲方那边急了
