### ISSUE TITLE
大概网站功能

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#6]
![benzex](https://f.cloud.github.com/assets/4066386/1571539/633ffebc-5107-11e3-9e4d-5f6799d1327a.png)

熊叔 我写了一个网站大概的功能列表 你看看有什么问题么 如果没有问题我就发给张驰 回头我们就按照这个来开发啦~

**Comment by bearice** [comment]
没有问题。
数据结构我就按照superne那里照抄了。

**Comment by zhuangya** [comment]
好的。
