### ISSUE TITLE
邮箱注册的用户，获取信息的时候，结构和weibo登录的用户不一致

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#64]
```
{
  "id": "53078fe16d4bb9cd07000003",
  "name": "God",
  "email": "god@heaven.co",
  "flags": []
}

```

现在是这样，然后weibo那边是有一个 key 叫做 `_json`

然后 weibo 登陆的用户是有取 `_json` 里面的信息的。。

现在结构变了之后， js 就报错 `TypeError: Cannot read property '_json' of undefined` TT TT

**Comment by bearice** [comment]
那个_json是weibo给的，email注册我上哪找这个去啊（

**Comment by zhuangya** [comment]
我这边hold住了 =)
