### ISSUE TITLE
无法用weibo登录

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#65]
@zhuangya 
在网站上选择用微博登录 就会跳转到如下界面
![2014-02-22 4 53 46](https://f.cloud.github.com/assets/4066386/2237316/0b50a976-9b9f-11e3-8271-7b8565d9b2df.png)

**Comment by zhuangya** [comment]
@bearice 你看这是啥问题？

**Comment by bearice** [comment]
似乎是你已经登陆过了，再次登陆就这样了。
