### ISSUE TITLE
网站建设尾项

### ISSUE THREAD

**Issue by wan9** [zhuangya/nova#71]
首先要说的是 @zhuangya 那边给张驰开一个帐号 好方便他能看到网站的点击率

其次是刚张驰那边给我打了电话 
基本上来说就是对我们做的网站很不满意 
更不要说拖了这么久
所以现在尾款他就不愿意结了 服务器的钱就是一年1060的费用他再给一下 然后就这样

接下来这一年就辛苦各位维护了 @bearice 谢谢各位

**Comment by wan9** [comment]
@zhuangya 
给后台加一个功能 就是可以管理/上传 现在benzex.com各个页面的图
以及可以更改联系我们的内容

**Comment by zhuangya** [comment]
现在还需要做的一个事情是传上去 默认的背景图片。

所以部署的事情延迟一下，晚些再搞。

@bearice 现在可不要部署呀。 =)
